apiVersion: v1
entries:
  landing-page:
  - apiVersion: v2
    appVersion: 0.6.2
    created: "2024-02-22T09:01:19.46685577+01:00"
    dependencies:
    - import-values:
      - defaults
      name: helmet
      repository: https://companyinfo.github.io/helm-charts
      version: ^0.10.1
    description: bran.tech landing page
    digest: f3aca63c03a7f9410de53b15a84b31b414063f5882b9b7cd7f5a79dfcd5f7c88
    home: https://github.com/bran-tech/landing-page
    kubeVersion: '>=1.23.0-0'
    maintainers:
    - email: bpteodor@users.noreply.github.com
      name: Teo
    name: landing-page
    urls:
    - https://bran-tech.github.io/helm/charts/landing-page-0.3.3.tgz
    version: 0.3.3
  - apiVersion: v2
    appVersion: 0.6.0
    created: "2024-02-22T09:01:19.465611547+01:00"
    dependencies:
    - import-values:
      - defaults
      name: helmet
      repository: https://companyinfo.github.io/helm-charts
      version: ^0.10.1
    description: bran.tech landing page
    digest: 893d4d9dca2b958d73af962801d581c9e37a584cc706143d62d6267b5fb4bd3d
    home: https://github.com/bran-tech/landing-page
    kubeVersion: '>=1.23.0-0'
    maintainers:
    - email: bpteodor@users.noreply.github.com
      name: Teo
    name: landing-page
    urls:
    - https://bran-tech.github.io/helm/charts/landing-page-0.3.2.tgz
    version: 0.3.2
  - apiVersion: v2
    appVersion: 0.6.0
    created: "2024-02-22T09:01:19.463752028+01:00"
    dependencies:
    - import-values:
      - defaults
      name: helmet
      repository: https://companyinfo.github.io/helm-charts
      version: ^0.10.1
    description: bran.tech landing page
    digest: f19fd7a5e294d887137f22639c3ef325990e96e6cb8779c52c694a75d053590d
    home: https://github.com/bran-tech/landing-page
    kubeVersion: '>=1.23.0-0'
    maintainers:
    - email: bpteodor@users.noreply.github.com
      name: Teo
    name: landing-page
    urls:
    - https://bran-tech.github.io/helm/charts/landing-page-0.3.1.tgz
    version: 0.3.1
  - apiVersion: v2
    appVersion: 0.5.0
    created: "2024-02-22T09:01:19.462467775+01:00"
    dependencies:
    - import-values:
      - defaults
      name: helmet
      repository: https://companyinfo.github.io/helm-charts
      version: ^0.10.1
    description: bran.tech landing page
    digest: 37956660b9493f57aa81279051fd4f50d85a44f110036a2a0671c072d96d5d9e
    home: https://github.com/bran-tech/landing-page
    kubeVersion: '>=1.23.0-0'
    maintainers:
    - email: bpteodor@users.noreply.github.com
      name: Teo
    name: landing-page
    urls:
    - https://bran-tech.github.io/helm/charts/landing-page-0.3.0.tgz
    version: 0.3.0
  - apiVersion: v2
    appVersion: 0.5.0
    created: "2024-02-22T09:01:19.460860654+01:00"
    description: bran.tech landing page
    digest: a7052e30dc4ff1cec545dccd7b0cf457865942b6dd386f2afcb3297dc19f8fe8
    home: https://github.com/bran-tech/landing-page
    kubeVersion: '>=1.23.0-0'
    maintainers:
    - email: bpteodor@users.noreply.github.com
      name: Teo
    name: landing-page
    urls:
    - https://bran-tech.github.io/helm/charts/landing-page-0.2.1.tgz
    version: 0.2.1
  - apiVersion: v2
    appVersion: 0.5.0
    created: "2024-02-22T09:01:19.460542166+01:00"
    description: bran.tech landing page
    digest: 903d81d4d681f705a434b800ced68868999dfc19213d50e1ca0001fb2edb9ca1
    home: https://github.com/bran-tech/landing-page
    kubeVersion: '>=1.23.0-0'
    maintainers:
    - email: bpteodor@users.noreply.github.com
      name: Teo
    name: landing-page
    urls:
    - https://bran-tech.github.io/helm/charts/landing-page-0.2.0.tgz
    version: 0.2.0
  poste-io:
  - apiVersion: v2
    appVersion: 2.3.19
    created: "2024-02-22T09:01:19.467410947+01:00"
    description: Fully functional mail server with free version
    digest: 4d3c570b303ae312a7ab7064f8b0a7c579b5673dfc4ff477fe17a94a3c0afb65
    home: https://poste.io/
    icon: https://poste.io/favicon.ico
    keywords:
    - mail
    - poste.io
    kubeVersion: '>=1.23.0-0'
    maintainers:
    - email: bpteodor@users.noreply.github.com
      name: Teo
    name: poste-io
    sources:
    - https://github.com/bran-tech/poste-io
    urls:
    - https://bran-tech.github.io/helm/charts/poste-io-0.2.0.tgz
    version: 0.2.0
generated: "2024-02-22T09:01:19.459458672+01:00"
